name: build

on:
  push:
    branches:
    - master

jobs:
  archimages:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
        - amd64
        - arm
        - arm64
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - id: set_build_date
      name: Set build date
      run: echo "::set-output name=build_date::$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    - name: Compile
      env:
        GOOS: linux
        GOARCH: ${{ matrix.arch }}
        CGO_ENABLED: '0'
        GO111MODULE: 'on'
      run: go build -v -ldflags "-X main.version=${{ github.sha }}" -a -tags netgo -o release/linux/${{ matrix.arch }}/drone-github-release ./cmd/drone-github-release
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: '.'
        file: docker/Dockerfile.linux.${{ matrix.arch }}
        platforms: linux/${{ matrix.arch }}
        push: true
        tags: ghcr.io/sigmaris/drone-github-release:latest-${{ matrix.arch }}
        labels: |
          org.label-schema.build-date=${{ steps.set_build_date.outputs.build_date }}
          org.label-schema.vcs-ref=${{ github.sha }}
          org.opencontainers.image.source=https://github.com/sigmaris/drone-github-release
  combine:
    needs: archimages
    runs-on: ubuntu-20.04
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Combine arch images
      run: >-
        docker manifest create ghcr.io/sigmaris/drone-github-release:latest
        --amend ghcr.io/sigmaris/drone-github-release:latest-amd64
        --amend ghcr.io/sigmaris/drone-github-release:latest-arm
        --amend ghcr.io/sigmaris/drone-github-release:latest-arm64
    - name: Push combined manifest
      run: docker manifest push ghcr.io/sigmaris/drone-github-release:latest
